### PR TITLE
Fix intake subsystem and rework subsystems to match final robot hardware.

### LINKED ISSUE #39: Finalize program for competition robot
The competition robot has subtly different hardware. Change necessary code to work with hardware on the actual robot.

### PR DESCRIPTION
**Pull request by sonicbhoc**
Fixes #39.

This change completes the initial work on the Intake subsystem and shooting commands, as well as ensuring that our subsystems reflect the hardware on the actual robot.

### CODE REVIEW

File: src/main/java/org/frc571/bradley/commands/LowerIntake.java [hunk 1]
```diff
@@ -1,43 +1,46 @@
...
+import edu.wpi.first.wpilibj2.command.CommandBase;
+
+public class LowerIntake extends CommandBase {
+    final IntakeArms arm;
+    boolean first = true;
+
+    final IntakeArms.ArmDirection dir;
+
+    public LowerIntake() {
+        this.dir = IntakeArms.ArmDirection.DOWN;
```
Comment (fishyfishfish55) [inline src/main/java/org/frc571/bradley/commands/LowerIntake.java]: Remove unnecessary use of this keyword

File: src/main/java/org/frc571/bradley/commands/RaiseIntake.java [hunk 2]
```diff
@@ -1,16 +1,20 @@
...
+    final IntakeArms arm;
+    boolean first = true;
 
-    public RaiseIntake() {
-        arm = IntakeArm.getInstance();
+    final IntakeArms.ArmDirection dir;
 
-        addRequirements(arm);
+    public RaiseIntake() {
+        this.dir = IntakeArms.ArmDirection.UP;
```
Comment (fishyfishfish55) [inline src/main/java/org/frc571/bradley/commands/RaiseIntake.java]: Remove unnecessary use of this keyword

**Review by fishyfishfish55 — CHANGES_REQUESTED** [review]
Remove unnecessary use of this keyword; see comments

**Review by fishyfishfish55 — APPROVED** [review]
Looks good!
