### PR TITLE
Fix DriveCommand to continuously stream values

### LINKED ISSUE #66: Joystick not responsive
Joystick appears to be stuck at a value of 0.

### PR DESCRIPTION
**Pull request by sonicbhoc**
By changing DriveCommand to accept Double instead of DoubleSupplier,
only the initial value was read. This change restores reading a
stream of double values instead.

Closes #66.

### CODE REVIEW

File: src/main/java/org/frc571/bradley/Controller.java [hunk 1]
```diff
@@ -1,9 +1,10 @@
 package org.frc571.bradley;
 
 public class Controller {
-    public static double ApplyJoystickDeadzone(double value, double deadzone) {
+    public static double ApplyJoystickDeadzone(double rawValue, double deadzone) {
         double result;
         double validRange = Constants.ControlConstants.MAX_AXIS - deadzone;
+        double value = Math.abs(rawValue);
```
Comment (fishyfishfish55) [inline src/main/java/org/frc571/bradley/Controller.java:7]: Rename `rawValue` to `value` and remove this assignment. Use `Math.abs(value)` in `if` statement. This also has the benefit of keeping the original, simple `return` statement.

File: src/main/java/org/frc571/bradley/commands/DriveCommand.java [hunk 2]
```diff
@@ -28,7 +30,7 @@ public void initialize() {
     // Called every time the scheduler runs while the command is scheduled.
     @Override
     public void execute() {
-        m_drive.drive(m_forward * Math.abs(m_forward)*0.60, -m_turn * 0.30);
+        m_drive.drive(m_forward.getAsDouble() * Math.abs(m_forward.getAsDouble())*0.60, -m_turn.getAsDouble() * 0.30);
```
Comment (fishyfishfish55) [inline src/main/java/org/frc571/bradley/commands/DriveCommand.java]: Remove magic numbers

**Review by fishyfishfish55 — CHANGES_REQUESTED** [review]
Remove magic numbers and simplify `applyJoystickDeadzone`

File: src/main/java/org/frc571/bradley/Controller.java (hunk 1 above)
Comment (sonicbhoc) [reply src/main/java/org/frc571/bradley/Controller.java:7]: This change would require me to call Math.abs twice instead of once. As it is now, the function works and is easy-to-read. I do not suggest modifying it.

**Review by fishyfishfish55 — APPROVED** [review]
